nelmio_api_doc:
    documentation:
        servers:
            - url: https://localhost
              description: Web over HTTPS
        info:
            title: Social Network
            description: A project based on DDD, CQRS, and HA made with Symfony web framework.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)(?!/doc.json$)  # Accepts routes under /api except /api/doc
