nelmio_api_doc:
    areas: # to filter documented areas
        default:
            path_patterns: [ /api/doc.json ]
        network:
            path_patterns: [ ^/api/network ]
            
    documentation:
        servers:
            - url: https://localhost
              description: Web over HTTPS
        info:
            title: Social Network
            description: A project based on DDD, CQRS, and HA made with Symfony web framework.
            version: 1.0.0
            
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
